### ISSUE TITLE
How to know when a field is validating?

### ISSUE THREAD

**Issue by andreasciamanna** [jaredpalmer/formik#415] opened 2018-02-08 11:09 UTC
I have configured a YUP validation schema with a `test` condition, which sends the value to the server, through `fetch` to validate that value.
You can imagine this as a typical scenario: someone enters a new username and the app checks that it does not already exist.

The difference is that it's a list of a few boxes (usually two or three) with domains which need to be validated by the server.

Each text box has the following YUP configuration:
1. It's a string
2. It's required
3. (not yet implemented) it validates the value as a properly formed domain (not URL)
4. It validates the domain (again, using `fetch`)

I'd like to be able to not run **4** if **2** or **3** fail, but that's a different topic.

Even though each request is fairly quick, I'd like to display a feedback next to each text box being validated.

As far as I can see, unlike for `touched` and `errors`, there isn't a `validating[value_name]` prop in Formik or something similar. 

Maybe I'm looking at the wrong place?

**Comment by jaredpalmer** [comment] 2018-02-22 15:04
Duplicate of #126

**Closed by jaredpalmer** 2018-02-22 15:04 UTC

**Comment by cryve** [comment] 2018-07-18 15:41
@jaredpalmer This is not a duplicate. The `isValidating` prop discussed in #126 is for the whole form and you cannot tell the validation state of a single field by that.
