### ISSUE TITLE
Add `field.error` and `field.touched` support to `<Field>`

### ISSUE THREAD

**Issue by CodingDutchman** [jaredpalmer/formik#963] opened 2018-10-05 04:10 UTC
I'm pretty new to Formik, but one of the things I loved about it right away was the ability to wrap existing form field components with a `<Field>` and then use `value={field.value}` on my field component's props. 

My field components also display stylized errors if passed to the error prop. I first tried accessing the field's error value using `field.error`, but eventually realized I couldn't get the field's error value that way, and would need to use the `form` prop. 

Unfortunately (and this may be a separate issue), using `form.errors[field.name]` did not work for me, but using the lodash-style `getIn(form.errors, field.name)` did work. I suspect this might be due to nested-arrays in my values/errors model, but I have not yet had time to prove this out.

## Suggested Solution ##
So I'm suggesting that `field` should support `field.error` and `field.touched` as convenience handles over using `form.errors` or `form.touched`. Also be sure these accessors will work when there are nested arrays in the form model.

Example:
When:
`field.name` = `parents[0].children[0].firstName`, 
and 
`field.value` = `form.values.parents[0].children[0].firstName`
then:
`field.error` = `form.errors.parents[0].children[0].firstName`
and
`field.touched` = `form.touched.parents[0].children[0].firstName`

## Who does this impact? Who is this for?
As a Formik beginner I think this would make things simpler for other beginners.

**Comment by jaredpalmer** [comment] 2018-10-08 15:59
In Formik 2, a `meta` property is in discussion (it would be breaking). The other idea is to provide a `getFieldMeta` getter function.

**Comment by CarlosGines** [comment] 2018-12-09 16:31
I find this proposal quite convenient! Please don't clóset this issue Mr. Bot xD

**Comment by penx** [comment] 2019-01-16 10:43
This is a duplicate of the following:

https://github.com/jaredpalmer/formik/issues/343
https://github.com/jaredpalmer/formik/issues/828
https://github.com/jaredpalmer/formik/pull/579

**Closed** 2019-01-25 18:04 UTC
Labels: duplicate
