### ISSUE TITLE
Real-time validation before submitting a form or clicking away from a field

### ISSUE THREAD

**Issue by meysamzi** [jaredpalmer/formik#3731] opened 2023-02-23 15:32 UTC
Feature request
Real-time validation

Current Behavior
In Formik, you can't validate fields real-time, they only start validating when you submit your form or click away from a field

Desired Behavior
i want it to start validating when i first start typing in the field not before submitting my form or touch tab on keyboard or click away from the field, it must work like onchange event.

Who does this impact? Who is this for?
this will impact everybody

**Comment by psecuresystem** [comment] 2023-02-26 15:43
I love this. I would love to work on this. Can I go ahead Maintainers?

**Comment by meysamzi** [comment] 2023-02-27 17:40
> I think this already exists.

Would you help me find it

**Comment by SohanPathak-Velocity** [comment] 2023-03-01 12:43
There are two events to implement such behaviour, you can configure as you want.
- [validateOnBlur](https://formik.org/docs/api/formik#validateonblur-boolean) 
- [validateOnChange](https://formik.org/docs/api/formik#validateonchange-boolean)

**Comment by somic723** [comment] 2023-03-13 10:08
@meysamzi  if the problem is solved, please close this issue

**Closed** 2023-05-27 15:21 UTC
Labels: Type: Feature Request
