### ISSUE TITLE
Could `submitForm()` return a promise?

### ISSUE THREAD

**Issue by danhayden** [jaredpalmer/formik#79] opened 2017-07-22 09:54 UTC
If `submitForm()` returned a promise we could do things like below which would be extremely useful.

```js
class WrapperComponent extends Component {
  state = {
    values: null,
    errors: null
  }

  onClick = () => {
    this.form.submitForm().then(() => {
      const {values, errors} = this.form.state
      this.setState({values, errors})
    })
  }

  render () {
    return (
      <div>
        <FormikForm ref={node => (this.form = node)} />
        <button onClick={this.onClick}>submit</button>
        <pre>{JSON.stringify(this.state.paylaod, null, 2)}</pre>
        <pre>{JSON.stringify(this.state.errors, null, 2)}</pre>
      </div>
    )
  }
}
```

My end goal here is to have a form that can be either self contain (as a standard form would be) or controlled and utilised by a wrapper component.

**Comment by jaredpalmer** [comment] 2017-07-22 19:54
Duplicate of #42

**Comment by jaredpalmer** [comment] 2017-07-22 19:55
Duplicate of #25

**Closed by jaredpalmer** 2017-07-22 19:54 UTC
