### ISSUE TITLE
Field props not passed to wrapped function

### ISSUE THREAD

**Issue by simo-eskalera** [jaredpalmer/formik#1495] opened 2019-05-08 18:29 UTC
Hello, 
Thanks for making such an awesome lib. I'm not seeing Field props passed on to the inner render function. Here's my use case:

```
// consider this material-ui text field helper:
export const fieldToMUITextField = ({ field, disabled = false, ...props }) => {
  // other features defined here....omitted for illustration
  return {
    ...props,
    ...field,
    disabled: isSubmitting || disabled
  };
};
```
Then using the helper to wrap some repetitive functionality like error handling, I was expecting the disabled prop to be passed on to props, but it's not:
```
<Field name="someField" disabled={true}>
  { props => (
    <MUITextField ...fieldToMUITextField(props) />
  )}
</Field>
```

The problem code is the bag being passed on to the render function does not contain the extra props:
https://github.com/jaredpalmer/formik/blob/master/src/Field.tsx#L172

However, the documentations says: 
> Field's render props are an object containing:
> - field
> - form
> - **Any other props passed to field**

I have a feeling this was a deliberate decision, but I hope you can see its usefulness in this case as well.

**Comment by jjt** [comment] 2019-06-17 01:29
Same with a [`render` prop](https://github.com/jaredpalmer/formik/blob/master/src/Field.tsx#L167-L169) but, [`component` passes along the extra props](https://github.com/jaredpalmer/formik/blob/master/src/Field.tsx#L176-L180)

**Comment by jaredpalmer** [comment] 2019-06-17 17:36
Duplicate of #1371

**Closed by jaredpalmer** 2019-06-17 17:36 UTC
