### ISSUE TITLE
If an array within initialValues contains separate inputs referencing the same object, the values of those inputs are linked

### ISSUE THREAD

**Issue by 56839** [jaredpalmer/formik#1223] opened 2019-01-04 19:38 UTC
### Current Behavior

If values within `initialValues` refer to the same object, the values of those fields are linked. i.e. If I change the value of the first input, the second input changes, and vice versa. 

```javascript
const person = { name: "John" };

const Form = () => (
  <Formik
    initialValues={{
      people: [person, person]
    }}
    render={props => (
      <Fragment>
        {[0, 1].map(i => (
          <div key={i}>
            Name of person #{i}: <Field name={`people[${i}].name`} />
          </div>
        ))}
      </Fragment>
    )}
  />
);
```

If I change `initialValues` from `{people: [person, person]}` to
```javascript
{
  people: [ { name: 'John' }, { name: 'John' } ]
}
```
the fields operate independently, as expected.

### Expected behavior

I expect the fields to operate independent of one another.

### Reproducible example

https://codesandbox.io/s/42pm546q1w

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.4.1
| React            | 16.5.2
| TypeScript       |
| Browser          | Chrome
| npm/Yarn         | 6.4.1
| Operating System | macOS 10.13.6

### PS

Formik is great, thanks for all the hard work.

**Comment by LimonSmorodina** [comment] 2019-01-11 09:35
Hello, you can try
`{people: [person, Object.assign({}, person)]}`
or (for deep copy):
`{people: [person, JSON.parse(JSON.stringify(person))]}`

**Comment by rovansteen** [comment] 2019-01-11 09:41
That’s not a formik bug, that’s how JavaScript works. If you assign an object to a variable you assign it by reference, not by its value. So in your example there’s only one object stored in memory and when it’s mutated all variables reference that mutated object. You can use a method like mentioned above 👆🏻to copy without a reference to the original object. You can also use the new spread operator to get the same effect. `const copy = {...person}`

**Comment by rovansteen** [comment] 2019-01-11 14:54
I agree with you that it's confusing and I have struggled with this in the past when I was learning JS. However, I don't think libraries should work around this behavior as that would be even more confusing for users as they only sometimes encounter this, based on the libraries they use. I'd consider your example as a bad practice and something that should be avoided. I get it's frustrating if you don't know why but it is part of learning the language (the good parts *and* the bad parts).

**Comment by 56839** [comment] 2019-01-11 15:15
I'm pretty familiar with JS, and I'm still surprised that the API works this way. I imagine most people would be surprised by it. Just because JS works that way doesn't mean Formik's API should work that way. It'd be easy to circumvent -- just add the step you described to wherever Formik is building its initial state.

Why not take care of that logic inside the library? Let's say Formik used the *values* of `initialValues` instead of the references to build its state. Would that be more or less confusing than how things currently stand? As it stands, Formik's state is permanently dictated by something outside of its control. That's bound to cause more problems than just this, right?

I'm sure I'm not the first person to raise this question, so I'm sure the smart folks behind Formik have considered this. I'm genuinely interested in having my mind changed if there's something I'm missing.

**Comment by jaredpalmer** [comment] 2019-01-11 19:03
Closing this as it is not a bug for the reasons above. Formik works just like React does here.

**Closed by jaredpalmer** 2019-01-11 19:03 UTC
