### ISSUE TITLE
Calling setFieldValue with en empty array remove the value in formik state

### ISSUE THREAD

**Issue by loicbourg** [jaredpalmer/formik#2151] opened 2019-12-26 08:14 UTC
## 🐛 Bug report

Hello, I encountered a strange behavior when trying to use formik with react select.

### Current Behavior

When we pass an empty array to *setFieldValue* the value of the field is removed from the state of formik.

### Expected behavior

The new value of the field should be an empty array.
 
### Reproducible example

https://codesandbox.io/s/formik-15x-react-select-v2-example-v5elr

### Suggested solution(s)

Is there any reasons to not always set the new value of the formElement in the formik state ? 

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | latest |
| React            | 16.9.0 |
| TypeScript       | N/A  |
| Browser          | chrome |
| npm/Yarn         | 1.19.1 |
| Operating System | debian 10 |

Happy holidays !

**Comment by spawluk** [comment] 2019-12-27 11:24
It is caused by https://github.com/jaredpalmer/formik/commit/9da32887cf61bdb2d08be90d863b35d537ebfe7c

**Comment by spawluk** [comment] 2019-12-27 11:27
Duplicate https://github.com/jaredpalmer/formik/issues/2130

**Comment by Matheswaaran** [comment] 2019-12-30 07:41
Then How can I pass an empty array to a form value and validate it? If the values get removed then the validation schema or validation function also gets broken

**Comment by Pasalietis** [comment] 2019-12-31 07:11
> Then How can I pass an empty array to a form value and validate it? If the values get removed then the validation schema or validation function also gets broken

use formik@2.0.6

**Comment by viniciusdacal** [comment] 2020-01-02 14:00
this has been fixed at 2.0.11. I think we can close it.

**Closed** 2020-01-06 20:32 UTC
