### ISSUE TITLE
Implementing Dark theme in the application

### ISSUE THREAD

**Issue by ashrafchowdury** [jaredpalmer/formik#3749] opened 2023-03-29 17:10 UTC
## Feature request

The purpose of this feature issue is to implement a **Dark Mode** feature in the application, which will provide users with an alternative colour scheme that is easier on the eyes and can help reduce eye strain.

**Comment by ashrafchowdury** [comment] 2023-03-29 17:13
I can add this **dark theme** with an Icon beside the **GitHub** icon on the Navbar if the feature makes sense can someone please assign me to work on this feature?

**Comment by probablyup** [comment] 2023-06-02 21:52
Duplicate of https://github.com/jaredpalmer/formik/issues/3741

**Closed by probablyup** 2023-06-02 21:52 UTC
Labels: Type: Feature Request
