### ISSUE TITLE
Validations are not working for dynamic fields in React Native

### ISSUE THREAD

**Issue by hussain-t** [jaredpalmer/formik#1540] opened 2019-05-22 08:42 UTC
## ❓Why are validations not working for dynamic fields in React Native?

I have dynamic fields in my React Native app. On every onPress event, a new set of fields are created within Formik. 

When I press a button which does handleSubmit, validations aren't fired for the dynamic fields. However if I touch the field and make it blur, validations are fired. I believe Formik doesn't know every time new fields are created. Is there a way I could let Formik know about the new fields.

![dynamic-fields-formik](https://user-images.githubusercontent.com/24408261/58160054-4c191c80-7c9b-11e9-81e8-d40cfde66cb5.gif)

Can someone please help me out with this issue?

**Comment by Andreyco** [comment] 2019-05-22 09:09
Code example, closing otherwise

**Comment by hussain-t** [comment] 2019-05-22 09:19
Please check this gist link.

https://gist.github.com/hussain-t/d574485cb596f8dd998c7471566732a2

Thanks :)

**Comment by Andreyco** [comment] 2019-05-22 15:48
The problem is you are registering fields later. What is not in initialValues is not marked as touched/validated (not sure, maybe this changed).

Your current state structure is as following.
```js
const INITIAL_VALUES = {
    founderName0: 'string',
    founderEmail0: 'string',
    // ...
}
```

Update it to this
```js
const INITIAL_VALUES = {
    founders: [
        {
             'name': 'string';
             'email': 'string';
        },
        // ...
    ]
}
```

Keeping data in array makes much more sense and will make work easier.

**Closed** 2019-05-22 15:50 UTC
Labels: Resolution: Needs More Information
