### ISSUE TITLE
Inaccurate documentation regarding `onSubmit`.

### ISSUE THREAD

**Issue by danpantry** [jaredpalmer/formik#1875] opened 2019-10-14 11:16 UTC
## 📖 Documentation

According to #828 (and [this][code] line of code), a consumer of Formik may return a Promise from their onSubmit function and Formik will handle setting the submitting status correctly - however, this is not [documented][docs]. Is this a mistake? Can I rely on the behaviour of Formik here or is it considered implementation detail?

I'm currently solving this problem in user-land and, when writing a test to verify it works as expected, I noticed that Formik already handled it :)

[code]: https://github.com/jaredpalmer/formik/blob/master/src/Formik.tsx#L645
[docs]: https://jaredpalmer.com/formik/docs/api/formik#onsubmit-values-values-formikbag-formikbag-void

**Comment by OfficerHalf** [comment] 2019-11-13 14:27
Dupe of #1957, should be fixed in #1987.

**Comment by jaredpalmer** [comment] 2020-01-07 18:24
Fixed in 2.x

**Closed** 2020-01-07 18:24 UTC
