### ISSUE TITLE
setFieldValue deleting the value

### ISSUE THREAD

**Issue by zsobral** [jaredpalmer/formik#2098] opened 2019-12-10 17:00 UTC
### Current Behavior

when use setFieldValue passing a empty array the field is deleted from the values

### Expected behavior

expected to set the field value to be an empty array

### Reproducible example

https://codesandbox.io/s/formik-codesandbox-template-leltv

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.0.7
| React            | 16.12.0
| TypeScript       |
| Browser          | chrome
| npm/Yarn         | yarn
| Operating System | linux

**Comment by rodymolenaar** [comment] 2019-12-11 06:58
This was introduced in `2.0.7` probably in https://github.com/jaredpalmer/formik/commit/9da32887cf61bdb2d08be90d863b35d537ebfe7c.

**Comment by eugenemlee** [comment] 2019-12-11 07:14
Yes, this change has broken all usage of `FieldArrays`. Could it please be reverted?

**Comment by jaredpalmer** [comment] 2019-12-11 18:35
Going to revert now.

**Comment by wingedearth** [comment] 2019-12-11 20:02
Simply reverting will bring back the bug of errors: { someField: [] } caused isValid to be false when it should be true for FieldArrays

**Comment by wingedearth** [comment] 2019-12-11 23:15
so the field with the empty array should be preserved for values but removed from errors (if there are no errors)

**Comment by wabi91** [comment] 2019-12-12 02:46
i have an another issue, i think something changed and it makes empty array issue and my issue
when use setFieldValue passing same length array what is not deep equal array with prev array, "FastField" component doesn't re-render.
it was not happened with version 2.0.6

**Comment by aleksavl** [comment] 2019-12-12 20:35
not fixed with latest realese

**Comment by Krasnopir** [comment] 2019-12-13 09:26
I also returned to version 06. because all data in the form of an array is deleted if an empty array is returned - chips, radioGroup, etc...

**Comment by alexe-dev** [comment] 2019-12-16 12:41
hi. any updates on this?

**Comment by tylerwray** [comment] 2019-12-17 05:36
FYI, this also breaks when explicitly setting a value to `[]`

`setFieldValue('stuff', [])` sets the field `stuff` to undefined, which in our case, is an unwanted/breaking behavior. Should prob be a major version change for that.

Thanks for all the awesome work on Formik. I ❤️ forms in React now b/c of Formik.

**Comment by bugzpodder** [comment] 2019-12-18 05:53
repro https://codesandbox.io/s/formik-example-934n6 but you probably don't need it.

**Comment by YufeeXing** [comment] 2019-12-20 02:40
it seems that 2.0.3 and 2.0.8 have the same problem

**Comment by DalerAsrorov** [comment] 2019-12-31 17:52
Still facing the same issue.

**Comment by viniciusdacal** [comment] 2020-01-02 14:06
@DalerAsrorov have you tried 2.0.11? It should be fixed in that version.

**Comment by donperi** [comment] 2020-01-03 15:18
I'm facing the same issue on 2.0.11.
Using `setFieldValue(field.name, [])` deletes the field from the form. 

I can't use `<FieldArray />` neither, as it doesn't allow custom props as `<Field />` does.

Ex:

```
<FieldArray
   component={CustomComponent}
   customPropForCustomCompoent="value"
/>
```
`customPropForCustomCompoent` will be missed.

**Comment by viniciusdacal** [comment] 2020-01-03 15:28
@donperi can you make a sandbox reproducing the issue? I tried this one and seems to be ok on 2.0.11 https://codesandbox.io/s/formik-example-6021m
(Change the email and see the props output)

**Comment by donperi** [comment] 2020-01-03 15:33
Sure @viniciusdacal, but give me some time. I'm busy with another stuff atm.

**Comment by jaredpalmer** [comment] 2020-01-06 19:28
Can someone make a PR?

**Comment by jaredpalmer** [comment] 2020-01-06 19:28
Im out of office this week

**Comment by viniciusdacal** [comment] 2020-01-06 19:30
I tested on latest version and it's working ok for me. If we manage to get a sandbox which we can repro the issue, I can work on it.

**Comment by zsobral** [comment] 2020-01-06 19:35
I'm using 2.1.1 now, the issue was solved for me

**Comment by DalerAsrorov** [comment] 2020-01-06 19:42
I will upgrade to `2.1.1` and see if it works for me too.

**Comment by jaredpalmer** [comment] 2020-01-06 19:49
I believe this was fixed in the latest release

**Closed by jaredpalmer** 2020-01-06 19:49 UTC
Labels: Component: FieldArray, Type: Bug, Type: Regression

**Comment by alegri1** [comment] 2020-01-09 13:01
Just updated to 2.1.1 now and can confirm that the issue is resolved for me

**Comment by Krasnopir** [comment] 2020-01-09 13:15
confirm - everything is ok

**Comment by fgatti675** [comment] 2020-06-26 13:50
Anyone experiencing the same issue when setting the value to `0` ?
When I set the value to 0 like that, the textfield displays no value with Formik 2.1.4
